name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # 必要なPythonのバージョンを指定

      # 依存関係をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # テストを実行
      - name: Run tests
        run: |
          python -m unittest discover

